/*
** Copyright 2024,2025 INRIA
**
** Contributors :
** Romain PEREIRA, rpereira@anl.gov
**
** This software is a computer program whose purpose is to execute
** blas subroutines on multi-GPUs system.
**
** This software is governed by the CeCILL-C license under French law and
** abiding by the rules of distribution of free software.  You can  use,
** modify and/ or redistribute the software under the terms of the CeCILL-C
** license as circulated by CEA, CNRS and INRIA at the following URL
** "http://www.cecill.info".

** As a counterpart to the access to the source code and  rights to copy,
** modify and redistribute granted by the license, users are provided only
** with a limited warranty  and the software's author,  the holder of the
** economic rights,  and the successive licensors  have only  limited
** liability.

** In this respect, the user's attention is drawn to the risks associated
** with loading,  using,  modifying and/or developing or reproducing the
** software by the user in light of its specific status of free software,
** that may mean  that it is complicated to manipulate,  and  that  also
** therefore means  that it is reserved for developers  and  experienced
** professionals having in-depth computer knowledge. Users are therefore
** encouraged to load and test the software's suitability as regards their
** requirements in conditions enabling the security of their systems and/or
** data to be ensured and,  more generally, to use and operate it in the
** same conditions as regards security.

** The fact that you are presently reading this means that you have had
** knowledge of the CeCILL-C license and that you accept its terms.
**/

#ifndef __XKRT_BITSET2D_H__
# define __XKRT_BITSET2D_H__

# include <stdint.h>
# include <stdlib.h>

__XKRT_BITSET2D_H__

/** Generated by Claude Sonnet 4.6 with minor edits from Romain */

template<typename TYPE = uint64_t, typename INDEX_TYPE = int>
struct bitset2d_t
{
    static constexpr int BITS  = sizeof(TYPE) * 8;
    static constexpr int MASK  = BITS - 1;
    static constexpr int SHIFT = __builtin_ctz(BITS);

    const INDEX_TYPE  n;        // number of nodes
    const INDEX_TYPE  stride;   // words per row = ceil(n / BITS)
    TYPE *            words;    // flat array of n * stride words

    bitset2d_t(INDEX_TYPE n) :
        n(n),
        stride((n + BITS - 1) / BITS),
        words((TYPE*)calloc(n * stride, sizeof(TYPE)))
    {}

    ~bitset2d_t(void)
    {
        free(this->words);
    }

    // Row pointer for node i  (inline, zero overhead)
    inline TYPE*       row(INDEX_TYPE i)       { return this->words + i * this->stride; }
    inline const TYPE* row(INDEX_TYPE i) const { return this->words + i * this->stride; }

    // Set bit (i, j) — node i can reach node j
    inline void
    set(INDEX_TYPE i, INDEX_TYPE j)
    {
        row(i)[j >> SHIFT] |= (TYPE(1) << (j & MASK));
    }

    // Test bit (i, j)
    inline bool
    test(INDEX_TYPE i, INDEX_TYPE j) const
    {
        return (row(i)[j >> SHIFT] >> (j & MASK)) & TYPE(1);
    }

    // Clear bit (i, j)
    inline void
    clear(INDEX_TYPE i, INDEX_TYPE j)
    {
        row(i)[j >> SHIFT] &= ~(TYPE(1) << (j & MASK));
    }

    // row[i] |= row[j]  — node i inherits all of j's reachability
    inline void
    or_rows(INDEX_TYPE i, INDEX_TYPE j)
    {
        TYPE*       ri = row(i);
        const TYPE* rj = row(j);
        for (INDEX_TYPE w = 0; w < this->stride; ++w)
            ri[w] |= rj[w];
    }

    // Check if any bit in row[i] & row[j] is set
    inline bool
    rows_intersect(INDEX_TYPE i, INDEX_TYPE j) const
    {
        const TYPE* ri = row(i);
        const TYPE* rj = row(j);
        for (INDEX_TYPE w = 0; w < this->stride; ++w)
            if (ri[w] & rj[w])
                return true;
        return false;
    }

    // Clear entire row i
    inline void
    reset_row(INDEX_TYPE i)
    {
        memset(row(i), 0, this->stride * sizeof(TYPE));
    }

    // Clear everything
    inline void
    reset_all(void)
    {
        memset(this->words, 0, n * this->stride * sizeof(TYPE));
    }

    // Dump the n x n bit matrix to 'file', one row per line
    inline void
    dump(FILE * file) const
    {
        for (INDEX_TYPE i = 0; i < this->n; ++i)
        {
            for (INDEX_TYPE j = 0; j < this->n; ++j)
                fputc(this->test(i, j) ? '1' : '0', file);
            fputc('\n', file);
        }
    }
};

#endif /* __XKRT_BITSET2D_H__ */
